# Generated by Django 4.1 on 2024-09-20 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_registration",
                        message="Enter a valid license number in the format ABC12345.",
                        regex="^[A-Z]{3}\\d{5}$",
                    )
                ],
            ),
        ),
    ]
